version: "3"

tasks:
  repl:
    desc: Start a REPL
    silent: true
    interactive: true
    cmd: nix run .#repl

  deploy:
    desc: Deploy a machine
    silent: true
    cmd: ./scripts/deploy.nu {{ .CLI_ARGS }}

  create:
    desc: Create a machine
    silent: true
    cmd: ./scripts/create-machine.nu {{ .CLI_ARGS }}

  build-sd:
    desc: Build a SD card image
    silent: true
    cmds:
      - ./scripts/build-sd.nu /dev/disk5 {{ .CLI_ARGS }}

  clean:
    desc: Clean the nix store
    silent: true
    cmds:
      - nix-collect-garbage
      - nix-store --verify --check-contents --repair
      - ssh builder@linux-builder "nix-collect-garbage"
      - ssh builder@linux-builder "nix-store --verify --check-contents --repair"

  docgen:
    desc: Generate the documentation
    silent: true
    cmds:
      - nix run .#docgen

  nix-upgrade-darwin:
    silent: true
    internal: true
    platforms: [darwin]
    cmds:
      - nix-env --install --attr nixpkgs.nix
      - launchctl remove org.nixos.nix-daemon
      - launchctl load /Library/LaunchDaemons/org.nixos.nix-daemon.plist
      - sudo rm /etc/ssl/certs/ca-certificates.crt
      - sudo ln -s /nix/var/nix/profiles/default/etc/ssl/certs/ca-bundle.crt /etc/ssl/certs/ca-certificates.crt

  nix-upgrade-linux:
    silent: true
    internal: true
    platforms: [linux]
    cmds:
      - nix-env --install --attr nixpkgs.nix nixpkgs.cacert
      - systemctl daemon-reload
      - systemctl restart nix-daemon

  nix-upgrade:
    desc: Upgrade Nix in the current system
    silent: true
    cmds:
      - sudo nix-channel --update
      - task: nix-upgrade-linux
      - task: nix-upgrade-darwin
