apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.downstream.namespace }}
---
{{- range .Values.downstream.clusters }}
kind: Cluster
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.downstream.namespace }}
  labels: {{ .labels | default (dict) | toYaml | nindent 4 }}
spec:
  templateValues: {{ .values | default (dict) | toYaml | nindent 4 }}
  {{- if hasKey . "kubeConfigSecret" }}  
  kubeConfigSecret: {{ .kubeConfigSecret | quote }}
  kubeConfigSecretNamespace: {{ $.Values.downstream.namespace | quote }}
  {{- end }}
---
{{- if hasKey . "kubeConfigSecret" }}  
kind: Secret
apiVersion: v1
metadata:
  name: {{ .name }}-kubeconfig
  namespace: {{ $.Values.downstream.namespace }}
stringData:
  value: |-
    apiVersion: v1
    clusters:
    - cluster:
        server: https://cluster-{{ .name }}.{{ $.Values.tailnet }}:443
      name: default
    contexts:
    - context:
        cluster: default
        user: tailscale-auth
      name: default
    current-context: default
    kind: Config
    preferences: {}
    users:
    - name: tailscale-auth
      user:
        token: unused
---
{{- end }}
{{- end }} 

