apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.downstream.namespace }}
---
{{- range $.Values.downstream.clusters }}
kind: Cluster
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.downstream.namespace }}
  labels: {{ .labels | default (dict) | toYaml | nindent 4 }}
spec:
  templateValues: {{ .values | default (dict) | toYaml | nindent 4 }}
---
{{- end }} 

