{{- $labelsList := list }}
{{- range $key, $value := .Values.local.labels }}
    {{- $label := printf "%s=%s" $key $value }}
    {{- $labelsList = append $labelsList $label }}
{{- end }}
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-namespace-label
  namespace: fleet-local
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      serviceAccountName: local-cluster-patcher
      containers:
        - name: kubectl-container
          image: bitnami/kubectl
          env:
            - name: LABELS
              value: {{ join " " $labelsList | quote }}
            - name: VALUES
              value: {{ toJson .Values.local.values | quote }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Patch the namespace with the labels
              kubectl label -n fleet-local clusters.fleet.cattle.io local $LABELS --overwrite
              # Patch the custom resource to update spec.templateValues
              kubectl patch -n fleet-local clusters.fleet.cattle.io local --type=merge -p "{\"spec\":{\"templateValues\":${VALUES}}}"
      restartPolicy: OnFailure
