apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-cluster-patcher
  namespace: fleet-local
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: local-cluster-patcher
  namespace: fleet-local
rules:
  - apiGroups: ["fleet.cattle.io"]
    resources: ["clusters"]
    verbs: ["patch", "get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: local-cluster-patcher
  namespace: fleet-local
subjects:
  - kind: ServiceAccount
    name: local-cluster-patcher
    namespace: fleet-local
roleRef:
  kind: Role
  name: local-cluster-patcher
  apiGroup: rbac.authorization.k8s.io
