id = 1
platform = "x86_64-linux"
sshPublicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK0BMyBc8tGXvW5glx2VIIGKar26NVb3RQQBLPCLIqQh"
publicIP = "128.140.39.64"

[wg]
publicKey = "Juozjo5Mi2zPm0fwhHlo3b5956HtZOw0MxdYWOjA2XU="

[wg.server]
enable = true
port = 51_820
