id = 5
platform = "x86_64-darwin"
sshPublicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIKcwa/PgM3iOEzPdIfLwtpssHtozAzhU4I0g4Iked/LE"
localIP = "10.136.1.133"

[wg]
publicKey = "4Y/frov/D/Y2Fpf5QpHXQU1zKltS63rChNSPGPlDV2w="
