defaultNamespace: monitoring
helm:
  chart: "kube-prometheus-stack"
  repo: "https://prometheus-community.github.io/helm-charts"
  version: "56.6.2"

overrideTargets:
  - clusterSelector:
      matchExpressions:
        - key: prometheus
          operator: In
          values:
            - upstream
            - downstream
            - standalone

targetCustomizations:
  - name: upstream
    helm:
      values:
        grafana:
          ingress:
            enabled: true
            hosts: 
              - "grafana.${ .ClusterValues.hostname }.cluster"
            
