defaultNamespace: monitoring
helm:
  chart: "kube-prometheus-stack"
  repo: "https://prometheus-community.github.io/helm-charts"
  version: "56.6.2"
  values:
    grafana:
      ingress:
        enabled: true
        hosts: 
          - "grafana.${ .ClusterName }.cluster"
targetCustomizations:
  - name: everywhere
    clusterSelector: {}
            
  - name: skip
    clusterSelector: {}
    doNotDeploy: true
