defaultNamespace: monitoring
helm:
  chart: "kube-prometheus-stack"
  repo: "https://prometheus-community.github.io/helm-charts"
  version: "56.6.2"

targetCustomizations:
  - name: upstream
    clusterSelector:
      matchLabels:
        prometheus: "upstream"
    values:
      grafana:
        ingress:
          enabled: true
          hosts: 
            - "grafana.${ .ClusterValues.hostname }.cluster"
            
  - name: skip
    clusterSelector: {}
    doNotDeploy: true
