apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vpn-kubernetes-api
  namespace: kube-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`api.{{.Values.hostname}}.{{.Values.domain}}`) && ClientIP(`{{ index .Values.traefik.service.externalIPs 0 }}/{{Values.cidr}}`)
      kind: Rule
      services:
        - name: kubernetes
          namespace: default
          port: 443
          scheme: https
  tls:
    passthrough: true
