apiVersion: apps/v1
kind: DaemonSet
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.7.0
  name: kube-vip-ds
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.7.0
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/master
                  operator: Exists
              - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: Exists
      containers:
        - args:
          - manager
          image: ghcr.io/kube-vip/kube-vip:v0.7.0
          imagePullPolicy: Always
          name: kube-vip
          env:
          - name: address
            value: {{ .Values.vip }}
          # TODO
          - name: vip_loglevel
            value: "5"
          # - name: vip_interface
          #   value: "wlo1" # overriden by wg0 in wireguard mode?
          - name: vip_servicesinterface
            value: "wlo1"
          {{ if .Values.wireguard.enabled }}
          - name: vip_wireguard
            value: "true"
          {{ end }}
          # - name: vip_ddns
          #   value: "true"
          - name: lb_fwdmethod
            value: "nat"
          - name: enable_node_labeling
            value: "true"
          - name: prometheus_server
            value: :2112
          #- name: vip_arp # ! disable when using wireguard
          #  value: "true"
          - name: port
            value: "6443"
          - name: vip_cidr
            value: "16"
          - name: dns_mode
            value: first
          - name: cp_enable
            value: "true"
          - name: cp_namespace
            value: {{ .Release.Namespace }}
          - name: svc_enable
            value: "true"
          - name: svc_leasename
            value: plndr-svcs-lock
          - name: svc_election
            value: "true"
          - name: vip_leaderelection
            value: "true"
          - name: vip_leasename
            value: plndr-cp-lock
          - name: vip_leaseduration
            value: "5"
          - name: vip_renewdeadline
            value: "3"
          - name: vip_retryperiod
            value: "1"
          resources: {}
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
              - NET_RAW
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
  updateStrategy: {}
status:
  currentNumberScheduled: 0
  desiredNumberScheduled: 0
  numberMisscheduled: 0
  numberReady: 0

